
name: Build Packages

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up build environment
        run: |
          echo "wxvers=3.0.5.1 3.1.7 3.2.0" >> $GITHUB_ENV
          echo "wxsvgver=1.5.23" >> $GITHUB_ENV

      - name: Download wxWidgets sources
        run: |
          mkdir wxWidgets/ && cd wxWidgets/
          for ver in ${{ env.wxvers }}; do
            wget -O v${ver}.tar.gz https://github.com/wxWidgets/wxWidgets/archive/refs/tags/v${ver}.tar.gz
            tar -xzf v${ver}.tar.gz
          done

      - name: Download wxSVG source
        run: |
          ver=${{ env.wxsvgver }}
          mkdir wxSVG/ && cd wxSVG/
          wget -O v${ver}.tar.bz2 \
            https://sourceforge.net/projects/wxsvg/files/wxsvg/${ver}/wxsvg-${ver}.tar.bz2/download
          tar -xjf v${ver}.tar.bz2
