
name: Build Packages

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: install dependencies
        run: sudo apt install build-essential mingw-w64 pkgconf m4 autoconf automake

      - name: download packages
        run: python3 build.py download
